# Generated by Django 2.0.4 on 2018-04-09 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=200)),
                ('anime_type', models.CharField(choices=[('Movie', 'Movie'), ('TV', 'TV'), ('OVA', 'OVA'), ('Special', 'Special')], default='TV', max_length=7)),
                ('episodes', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('members', models.BigIntegerField()),
                ('anime_photo', models.ImageField(null=True, upload_to='img/profiles', verbose_name='Anime Photo')),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
    ]
