# Generated by Django 2.0.4 on 2018-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuOrganiserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
