# Generated by Django 2.0.4 on 2018-04-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuOrganiserApp', '0002_auto_20180409_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
