# Generated by Django 2.0.4 on 2018-04-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuOrganiserApp', '0004_auto_20180409_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('-rating',)},
        ),
    ]
