# Generated by Django 2.0.4 on 2018-04-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuOrganiserApp', '0006_auto_20180409_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_photo',
            field=models.ImageField(default="% static 'img/placeholder.jpg' %", null=True, upload_to='img/profiles', verbose_name='Anime Photo'),
        ),
    ]
