# Generated by Django 2.0.4 on 2018-04-10 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuOrganiserApp', '0008_auto_20180410_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV', 'TV'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('Special', 'Special')], default='TV', max_length=7),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
